package ben343.entities;

import java.util.Date;

import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.validation.constraints.NotNull;

@Entity
@Table(name = "MESSAGEAPP")
public class MessageApp {

	// ------------------------
	// PRIVATE FIELDS
	// ------------------------

	// An autogenerated id (unique for each user in the db)
	@Id
	@GeneratedValue(strategy = GenerationType.AUTO)
	private long id;
	
	// The message date
	@NotNull
	private String name;
	
	// The message date
	@NotNull
	private String email;

	// The message content
	@NotNull
	private String content;

	// The message date
	@NotNull
	private Date date;

	// ------------------------
	// PUBLIC METHODS
	// ------------------------

	public MessageApp() {
	}

	public MessageApp(long id) {
		this.id = id;
	}

	public MessageApp(String name, String email, String content, Date date) {
		this.name = name;
		this.email = email;
		this.content = content;
		this.date = date;
	}

	public long getId() {
		return id;
	}

	public void setId(long id) {
		this.id = id;
	}
	

	public String getContent() {
		return content;
	}

	public void setContent(String content) {
		this.content = content;
	}

	public Date getDate() {
		return date;
	}

	public void setDate(Date date) {
		this.date = date;
	}

	public String getName() {
		return name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getEmail() {
		return email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	public String toString() {
		return "[" + id + "] " + content + " - mail : " + date.toString();
	}
}
